apiVersion: v1
kind: Service
metadata:
  name: {{ include "opengauss.fullname" . }}-hl
  labels:
    {{- include "opengauss.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opengauss.selectorLabels" . | nindent 4 }}
